### ISSUE TITLE
aarch64 build reports as 32 bit

### ISSUE THREAD

**Issue by vfscalfani** [IUPAC-InChI/InChI#10]
This is likely a very minor issue. I successfully built `inchi-1` 1.07-beta.3 binary on Debian Bookworm (Raspberry Pi 5, aarch64) via the following:

```
cd InChI-1.07-beta.3/INCHI-1-SRC/INCHI_EXE/inchi-1/gcc
make
```
Then, running the binary (i.e., ./inchi-1), reports the following:

```
InChI version 1, Software v. 1.07 (inchi-1 executable)
Linux 32-bit Build (gcc 12.2.0) of Mar  4 2024 17:24:59 
...
...
```

However, inspecting the `./inchi-1` with `file` outputs:

```
file ./inchi-1
./inchi-1: ELF 64-bit LSB pie executable, ARM aarch64....
```
So, I think the file is indeed a 64 bit binary, but the console print statement reporting 32 bit is incorrect. I tried the build with x86 and it correctly recognizes the build as 64 bit. 

Thanks, 

Vin

**Comment by djb-rwth** [comment]
Hi Vin,
These sorts of messages are usually generated by GCC complier itself.
Please check if the GCC compiler generates the same kind of message if any C/C++ script is compiled.
Djordje

**Comment by djb-rwth** [comment]
Hi Vin,
It looks as if `aarch64` has not been considered whilst creating the output message regarding the OS.
I will add it in soon-to-be-released `1.07-Beta4` and kindly ask you to re-test this again.
Thank you in advance.

**Comment by djb-rwth** [comment]
Hi Vin,
`v.1.07-Beta4` has been uploaded, so please check if the issue has been resolved.
Thank you.

**Comment by vfscalfani** [comment]
Okay, I just built from the main branch and it now correctly reports a 64 bit build on aarch64. Thanks for the fix!

**Comment by djb-rwth** [comment]
Thanks for your time and effort in checking this.

**Comment by JanCBrammer** [comment]
@djb-rwth, could you link the commit that closes this issue?

**Comment by giallu** [comment]
> @djb-rwth, could you link the commit that closes this issue?

I think it's https://github.com/IUPAC-InChI/InChI/commit/f1fbd3ce81aa33584228931b6a1afd226f62d3c9

I also need to note, the code to set INCHI_BUILD_PLATFORM is duplicated in few places:
```
./INCHI-1-SRC/INCHI_BASE/src/util.h
./INCHI-1-SRC/INCHI_API/demos/inchi_main/src/e_util.h
./INCHI-1-SRC/INCHI_API/demos/mol2inchi/src/mol2inchi.h
```
and the fix only went to the first one, I think it could be advisable to centralize it in one place.
