### ISSUE TITLE
Atomic isotopes need to be fixed

### ISSUE THREAD

**Issue by stuchalk** [IUPAC-InChI/InChI#51]
This issue is posted based on a request to the submitter (Stuart Chalk) from the BIPM.  The BIPM's use case is to unambiguously identify isotopes of atoms that are used in the definition of standards for time and frequency (see https://www.bipm.org/en/publications/mises-en-pratique/standard-frequencies).

The current (and historical) InChI creation of single atoms of **common** elements is to convert them to the fully protonated form, for example:

- methane (CH4) InChI: InChI=1S/CH4/h1H4 [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/297)
- carbane (14CH4) InChI: InChI=1S/CH4/h1H4/i1+2 [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/26873)
  (this should be InChI=1S/C/i1+2 - Carbon-14)
- carbane (11CH4) InChI: InChI=1S/CH4/h1H4/i1-1 [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/114789)
   (this should be InChI=1S/C/i1-1 - Carbon-11)

whereas for other atoms of isotopes of other elements InChI gives what would be expected of a single atom.
- germanium-85 InChI: InChI=1S/Ge/i1-5 [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/6337084)

Please consider this a request to update the InChI code to improve the consistency of InChI generation.

**Comment by stuchalk** [comment]
Thanks for the quick response to this issue.  This makes complete sense to me that it is a molfile issue.  Let me circle back to PubChem with this information...

**Comment by gblanke02** [comment]
Beacsue this is a creation issue of the molfie that is digested by InChI the issue is under control of the molfile creator. In the examples above it depends on the rules of PubChem.
What has been recognized that the sketcher editor used in the InChI Web Demo is not able to create the appropriate molfiles as well. Instead we nused Biovia/Draw 2017 and copied the molfile into the "molfile section" of the InChI Web Demo.

**Comment by flange-ipb** [comment]
> What has been recognized that the sketcher editor used in the InChI Web Demo is not able to create the appropriate molfiles as well.

Unfortunately, the Ketcher structure editor we use in the InChI Web Demo has a bug in its Molfile export function where the valence 0 of atoms is not taken into account. [I already submitted a bug report](https://github.com/epam/ketcher/issues/5397).
