### ISSUE TITLE
SMILES?

### ISSUE THREAD

**Issue by ChemMitch** [IUPAC-InChI/InChI#63]
Is there a way to process SMILES using the inchi executable?

**Comment by JanCBrammer** [comment]
Not that I'm aware of. What's your use case?

**Comment by nnuk** [comment]
I would like elaborate a little here. So, until now we have only the options of either using a molfile or a SDF as an input format. You can also view this yourself when you run the inchi executable without any options. Below it shows the InChI usage format.

`Usage:
inchi-1 inputFile [outputFile [logFile [problemFile]]] [/option[ /option...]]
inchi-1 inputFiles... /AMI [/option[ /option...]]`

Also, we do have parameters that accept InChI string as an input but not SMILES. Actually, the InChI code base is yet not designed to accept SMILES. I hope it helps.

**Comment by fbaensch-beilstein** [comment]
@ChemMitch As @nnuk has already mentioned, the input is limited to mol and SD files. But we are always open to contributions.

If there's anything we can do to help you solve your problem, please let me know.

**Comment by ChemMitch** [comment]
Thank you, @fbaensch-beilstein , @nnuk 
I've found another way to get the InChIKey I was looking for.

**Comment by fbaensch-beilstein** [comment]
@ChemMitch glad you found a solution. So I will close this post.
Please don't hesitate to contact us if we can help you.
